import { useLoans } from '../context/LoanContext';

export default function AnalystDashboard() {
  const { loans, applications } = useLoans();

  // Financial calculations
  const totalLentValue = loans.reduce((sum, loan) => sum + Number(loan.amount), 0);
  
  // Risk Assessment: Flag loans with interest > 15% as "High Risk"
  const highRiskLoans = loans.filter(loan => Number(loan.interestRate) > 15);

  const formatMoney = (amount) => {
    return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(amount);
  };

  const handlePrintReport = () => {
    window.print();
  };

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-end border-b pb-4">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Financial Analysis & Risk</h1>
          <p className="text-gray-500 mt-2">Analyze loan data, assess risks, and generate reports.</p>
        </div>
        <button 
          onClick={handlePrintReport}
          className="bg-gray-800 hover:bg-black text-white px-4 py-2 rounded-md font-medium shadow-sm transition-colors flex items-center gap-2 print:hidden"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
          Export Report
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Financial Summary */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-lg font-bold text-gray-900 mb-4 border-b pb-2">Platform Financial Summary</h2>
          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-gray-600">Total Capital in Market</span>
              <span className="font-bold text-xl text-primary">{formatMoney(totalLentValue)}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-gray-600">Active Loan Offers</span>
              <span className="font-bold text-lg text-gray-800">{loans.length}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-gray-600">Pending Applications</span>
              <span className="font-bold text-lg text-gray-800">
                {applications.filter(a => a.status === 'pending').length}
              </span>
            </div>
          </div>
        </div>

        {/* Risk Assessment */}
        <div className="bg-red-50 p-6 rounded-xl shadow-sm border border-red-100">
          <h2 className="text-lg font-bold text-red-900 mb-4 border-b border-red-200 pb-2 flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
            Risk Assessment Flags
          </h2>
          {highRiskLoans.length === 0 ? (
            <p className="text-red-700 italic">No high-risk loans detected (Interest &gt; 15%).</p>
          ) : (
            <ul className="space-y-3">
              {highRiskLoans.map(loan => (
                <li key={loan.id} className="bg-white p-3 rounded-lg border border-red-200 shadow-sm flex justify-between items-center">
                  <div>
                    <span className="block font-bold text-gray-900">{formatMoney(loan.amount)}</span>
                    <span className="text-xs text-gray-500">Lender: {loan.lender}</span>
                  </div>
                  <span className="bg-red-100 text-red-800 px-2 py-1 rounded text-sm font-bold">
                    {loan.interestRate}% Rate
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
      
      {/* Print-only footer for reports */}
      <div className="hidden print:block mt-12 text-center text-sm text-gray-500">
        <p>Generated by Finova Landing Financial Analyst Dashboard</p>
        <p>Date: {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
}